# using REST Client extension for VSCode

### LOCALHOST
### localhost routes (3000 port)
GET http://localhost:3000

# get all users
GET http://localhost:3000/users

## get user by id
## for example: Ivan Karamazov
GET http://localhost:3000/users/672b8ad98727ea17a40f48b7

## add a new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Laura",
    "lastName": "Danney",
    "email": "lauradanney@gmail.com",
    "favoriteColor": "blush",
    "birthday": "1990-08-08"
}

## update user by id
PUT http://localhost:3000/users/672b88f38727ea17a40f48b2
Content-Type: application/json

{
    "firstName": "Dmitri",
    "lastName": "Karamazov",
    "email": "karamazovd@gmail.com",
    "favoriteColor": "burgundy",
    "birthday": "1920-10-10"
}

## delete user by id
DELETE http://localhost:3000/users/673660611e6e977424a3a664


### RENDER
### Render.com routes
https://project1-2rwd.onrender.com/

# get all users
GET https://project1-2rwd.onrender.com/users

# get user by id
# for example: Ivan Karamazov
GET https://project1-2rwd.onrender.com/users/672b8ad98727ea17a40f48b7

## add a new user
POST http://project1-2rwd.onrender.com/users
Content-Type: application/json

{
    "firstName": "Laura",
    "lastName": "Danney",
    "email": "lauradanney@gmail.com",
    "favoriteColor": "blush",
    "birthday": "1990-08-08"
}

## update user by id
## for example: Dmitri Karamazov's favorite color
PUT http://project1-2rwd.onrender.com/users/672b88f38727ea17a40f48b2
Content-Type: application/json

{
    "firstName": "Dmitri",
    "lastName": "Karamazov",
    "email": "karamazovd@gmail.com",
    "favoriteColor": "burgundy",
    "birthday": "1920-10-10"
}

## delete user by id
DELETE http://project1-2rwd.onrender.com/users/673660611e6e977424a3a664